<div class="col-sm-3 col-lg-3 shadow-lg pt-2 pr-3 pb-3  mb-5 bg-white text-left" style="min-height:336px;" id="div_btn">
    <a href="<?php echo base_url();?>My_Pages/myaccount" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left  <?php if($request['ACTION'] == 'myaccount' && !isset($request['SUB_ACTION'])) { echo 'active'; } ?>" role="button"  id="btn_download_link"><i class="fa fa-tachometer pull-left <?php if($request['ACTION'] == 'myaccount'  && !isset($request['SUB_ACTION'])) { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i>&nbsp;All data</a>
    <a href="<?php echo base_url();?>My_Pages/idcards" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left  <?php if($request['ACTION'] == 'idcards' && !isset($request['SUB_ACTION'])) { echo 'active'; } ?>" role="button"  id="btn_download_link"><i class="fa fa-eye pull-left <?php if($request['ACTION'] == 'idcards'  && !isset($request['SUB_ACTION'])) { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i>&nbsp;Preview I-Cards</a>
    <a  href="<?php echo base_url();?>My_Pages/idcards/reviewed" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left   <?php if($request['SUB_ACTION'] == 'reviewed') { echo 'active'; } ?>" role="button" id="btn_upload_photo" ><i class="fa fa-check-circle pull-left  <?php if($request['SUB_ACTION'] == 'reviewed') { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i>&nbsp;Reviewed I-Cards</a>
   
    
    
    <a  href="<?php echo base_url();?>My_Pages/idcards/inprocess" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left   <?php if($request['SUB_ACTION'] == 'inprocess') { echo 'active'; } ?>" role="button" id="btn_upload_link" ><i class="fa fa-cogs pull-left   <?php if($request['SUB_ACTION'] == 'inprocess') { echo 'text-white'; }else{ echo 'text-primary'; } ?> " ></i>&nbsp;In process I-Cards data</a>

    <a href="<?php echo base_url();?>My_Pages/myaccount/completed" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left  <?php if($request['SUB_ACTION'] == 'completed') { echo 'active'; } ?>" role="button"  id="btn_download_link"><i class="fa fa-check pull-left  <?php if($request['SUB_ACTION'] == 'completed') { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i>&nbsp;Completed I-Cards data</a>

   <!--  <a  href="<?php echo base_url();?>My_Pages/myaccount/draft" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-1  pb-2  pl-2 text-left   <?php if($request['SUB_ACTION'] == 'draft') { echo 'active'; } ?>" role="button" id="btn_upload_photo" ><i class="fa fa-inbox pull-left <?php if($request['SUB_ACTION'] == 'draft') { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i>&nbsp;Drafted I-Cards data</a> -->

    <a  href="<?php echo base_url();?>My_Pages/myaccount/pending" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left  <?php if( $request['SUB_ACTION'] == 'pending') { echo 'active'; } ?>" role="button" id="btn_data_entry_link" ><i class="fa fa-history pull-left  <?php if($request['SUB_ACTION'] == 'pending') { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i>&nbsp;Pending information data</a>
    <a  href="<?php echo base_url();?>My_Pages/idcards/pending_review" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-1  pb-2  pl-2 text-left   <?php if($request['SUB_ACTION'] == 'pending_review') { echo 'active'; } ?>" role="button" id="btn_upload_photo" ><i class="fa fa-inbox pull-left <?php if($request['SUB_ACTION'] == 'SUB_ACTION') { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i>&nbsp;Pending I-Cards</a> 

</div>
<div class="col-sm-3 col-lg-1 shadow-lg pt-2 pr-3 pb-3  mb-5 bg-white text-left" style="min-height:336px;" id="div_btn_collapsed" >
    <a href="<?php echo base_url();?>My_Pages/myaccount" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left  <?php if($request['ACTION'] == 'myaccount'  && !isset($request['SUB_ACTION'])) { echo 'active'; } ?>" role="button"  id="btn_download_link" title="All data" ><i class="fa fa-tachometer pull-left <?php if($request['ACTION'] == 'myaccount'  && !isset($request['SUB_ACTION']) ) { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i></a>
    <a href="<?php echo base_url();?>My_Pages/idcards" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left  <?php if($request['ACTION'] == 'idcards'  && !isset($request['SUB_ACTION'])) { echo 'active'; } ?>" role="button"  id="btn_download_link" title="Preview ID cards data" ><i class="fa fa-eye pull-left <?php if($request['ACTION'] == 'idcards'  && !isset($request['SUB_ACTION']) ) { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i></a>
    <a  href="<?php echo base_url();?>My_Pages/idcards/reviewed" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left   <?php if($request['SUB_ACTION'] == 'reviewed') { echo 'active'; } ?> " role="button" id="btn_upload_photo" title="Reviewed I-Cards data" ><i class="fa fa-check-circle pull-left   <?php if($request['SUB_ACTION'] == 'reviewed') { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i></a>
    
   

    <a  href="<?php echo base_url();?>My_Pages/myaccount/inprocess" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left   <?php if($request['SUB_ACTION'] == 'inprocess') { echo 'active'; } ?>" role="button" id="btn_upload_link" title="In process I-Cards data"><i class="fa fa-cogs pull-left  <?php if($request['SUB_ACTION'] == 'inprocess') { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i></a>

    <a href="<?php echo base_url();?>My_Pages/myaccount/completed" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left  <?php if($request['SUB_ACTION'] == 'completed') { echo 'active'; } ?>" role="button"  id="btn_download_link" title="Completed I-Cards data" ><i  class="fa fa-check pull-left <?php if($request['SUB_ACTION'] == 'completed') { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i></a>

    <!-- <a  href="<?php echo base_url();?>My_Pages/myaccount/draft" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left   <?php if($request['SUB_ACTION'] == 'draft') { echo 'active'; } ?> " role="button" id="btn_upload_photo" title="Drafted I-Cards data" ><i class="fa fa-inbox pull-left  <?php if($request['SUB_ACTION'] == 'draft') { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i></a> -->

    <a  href="<?php echo base_url();?>My_Pages/myaccount/pending" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left  <?php if( $request['SUB_ACTION'] == 'pending') { echo 'active'; } ?>" role="button" id="btn_data_entry_link" title="Pending information data" ><i class="fa fa-history pull-left  <?php if($request['SUB_ACTION'] == 'pending') { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i></a>
    <a  href="<?php echo base_url();?>My_Pages/idcards/pending_review" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left  <?php if( $request['SUB_ACTION'] == 'pending_review') { echo 'active'; } ?>" role="button" id="btn_data_entry_link" title="Pending  I-Cards" ><i class="fa fa-inbox pull-left   <?php if($request['SUB_ACTION'] == 'pending_review') { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i></a>

</div>