<div class="col-sm-3 col-lg-3 shadow-lg pt-2 pr-3 pb-3  mb-5 bg-white text-left  mr-1" style="min-height:336px;" id="div_btn">
    <a href="<?php echo base_url();?>id-cards" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left" role="button"  id="btn_download_link"><i class="fa fa-paint-brush pull-left text-primary" ></i>&nbsp;Create a new template</a>
    <a href="<?php echo base_url();?>My_Pages/created_templates" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left  <?php if($request['ACTION'] == 'created_templates') { echo 'active'; } ?>" role="button"  id="btn_download_link"><i class="fa fa-image pull-left " ></i>&nbsp;Created templates</a>
    <a  href="<?php echo base_url();?>My_Pages/ordered_templates" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left   <?php if($request['SUB_ACTION'] == 'ordered_templates') { echo 'active'; } ?>" role="button" id="btn_upload_link" ><i class="fa fa-shopping-cart pull-left <?php if($request['SUB_ACTION'] == 'ordered_templates') { echo 'text-white'; }else{ echo 'text-primary'; } ?>" ></i>&nbsp;Ordered Templates</a>
 </div>
<div class="col-sm-3 col-lg-1 shadow-lg pt-2 pr-3 pb-3  mb-5 bg-white text-left  mr-1" style="min-height:336px;" id="div_btn_collapsed" >
    <a href="<?php echo base_url();?>id-cards" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left" role="button"  id="" title="Create new template" ><i class="fa fa-paint-brush pull-left" ></i></a>
    <a href="<?php echo base_url();?>My_Pages/created_templates" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left  <?php if($request['ACTION'] == 'created_templates') { echo 'active'; } ?>" role="button"  id="btn_download_link" title="Download sample sheet" ><i class="fa fa-image pull-left " ></i></a>
    <a  href="<?php echo base_url();?>My_Pages/ordered_templates" class="mb-2 btn  btn-white btn-shadow  btn-rounded text-default pt-2  pr-2  pb-2  pl-2 text-left   <?php if($request['ACTION'] == 'ordered_templates') { echo 'active'; } ?>" role="button" id="btn_upload_link" title="Upload data excel"><i class="fa fa-shopping-cart pull-left" ></i></a>
 </div>